version: '3'

services:
  app:
    build: app/
    expose:
      - 5252
    restart: on-failure
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:2424"

  proxy:
    build: haproxy/
    ports:
      - 80:80
    depends_on:
      - app
  
  fluent-bit:
    image: fluent/fluent-bit:latest
    ports: 
      - 2424:2424
      - "2424:2424/udp"